# This configuration file example shows how to configure the srsRAN Project gNB to allow srsUE to connect to it. 
# This specific example uses ZMQ in place of a USRP for the RF-frontend, and creates an FDD cell with 10 MHz bandwidth. 
# To run the srsRAN Project gNB with this config, use the following command: 
#   sudo ./gnb -c gnb_zmq.yaml

amf:
  addr: 127.0.0.5                                              # The address or hostname of the AMF.
  bind_addr: 127.0.0.1                                            # A local IP that the gNB binds to for traffic from the AMF.

ru_sdr:
  device_driver: uhd                                              # The RF driver name.
  device_args: type=x300,send_frame_size=1472,recv_frame_size=1472 #,tx_port=0,rx_port=0 #nof_tx_streams=1,nof_rx_streams=1    # Optionally pass arguments to the selected RF driver.
  srate: 11.52                                                  # RF sample rate might need to be adjusted according to selected bandwidth.
  # otw_format: sc12  
  tx_gain: 31.5                                                     # Transmit gain of the RF might need to adjusted to the given situation.
  rx_gain: 37.5                                                     # Receive gain of the RF might need to adjusted to the given situation.                                          # Uplink eAxC port values.


cell_cfg:
  dl_arfcn: 368500 #640000 #368500                  # ARFCN of the downlink carrier (center frequency).
  band: 3 #78 #3                           # The NR band.
  channel_bandwidth_MHz: 10         # Bandwith in MHz. Number of PRBs will be automatically derived.
  common_scs: 15                    # Subcarrier spacing in kHz used for data.
  plmn: "90170"                     # PLMN broadcasted by the gNB.
  tac: 7                            # Tracking area code (needs to match the core configuration).
  pdcch:
    dedicated:
      ss2_type: common              # Search Space type, has to be set to common
      dci_format_0_1_and_1_1: false # Set correct DCI format (fallback)
  # pdsch:
  #   nof_ports: 0

log:
  filename: gnb.log            # Path of the log file.
  all_level: info                   # Logging level applied to all layers.
  hex_max_size: 0

pcap:
  mac_enable: true                 # Set to true to enable MAC-layer PCAPs.
  mac_filename: gnb_mac.pcap   # Path where the MAC PCAP is stored.
  ngap_enable: true                # Set to true to enable NGAP PCAPs.
  ngap_filename: gnb_ngap.pcap # Path where the NGAP PCAP is stored.